document.writeln("<footer class=\'main-footer\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("        <div class=\'row\'>");
document.writeln("            <div class=\'col-sm-4\'>");
document.writeln("                <div class=\'widget\'>");
document.writeln("                    <h4 class=\'title\'>友情链接</h4>");
document.writeln("                    <div class=\'content tag-cloud friend-links\'>");
document.writeln("                        <a href=\'http://www.bootcss.com/\' title=\'Bootstrap中文网\' onclick=\'_hmt.push([\'_trackEvent\', \'link\', \'click\', \'Bootstrap中文网\'])\' target=\'_blank\'>Bootstrap中文网</a>");
document.writeln("                        <a href=\'https://www.quanzhanketang.com/\' title=\'全栈课堂\' onclick=\'_hmt.push([\'_trackEvent\', \'link\', \'click\', \'全栈课堂\'])\' target=\'_blank\'>全栈课堂</a>");
document.writeln("                        <a href=\'https://www.webpackjs.com/\' title=\'Webpack中文网\' onclick=\'_hmt.push([\'_trackEvent\', \'link\', \'click\', \'Webpack中文网\'])\' target=\'_blank\'>Webpack中文网</a>");
document.writeln("                        <a href=\'https://www.nodeapp.cn/\' title=\'Node.js中文文档\' onclick=\'_hmt.push([\'_trackEvent\', \'link\', \'click\', \'Node.js中文文档\'])\' target=\'_blank\'>Node.js中文文档</a>");
document.writeln("                        <a href=\'http://www.91php.com/\' title=\'91PHP\' onclick=\'_hmt.push([\'_trackEvent\', \'link\', \'click\', \'91PHP\'])\' target=\'_blank\'>91PHP</a>");
document.writeln("                        <a href=\'http://www.rollupjs.com/\' title=\'Rollup中文文档\' onclick=\'_hmt.push([\'_trackEvent\', \'link\', \'click\', \'Rollup中文文档\'])\' target=\'_blank\'>Rollup中文文档</a>");
document.writeln("                        <a href=\'https://www.jquery123.com/\' title=\'jQuery中文网\' onclick=\'_hmt.push([\'_trackEvent\', \'link\', \'click\', \'jQuery中文网\'])\' target=\'_blank\'>jQuery中文网</a>");
document.writeln("                        <a href=\'https://www.npmjs.com.cn/\' title=\'NPM中文文档\' onclick=\'_hmt.push([\'_trackEvent\', \'link\', \'click\', \'NPM中文文档\'])\' target=\'_blank\'>NPM中文文档</a>");
document.writeln("                        <a href=\'http://www.sasschina.com/\' title=\'SASS中文网\' onclick=\'_hmt.push([\'_trackEvent\', \'link\', \'click\', \'SASS中文网\'])\' target=\'_blank\'>SASS中文网</a>");
document.writeln("                        <a href=\'http://www.golaravel.com/\' title=\'Laravel中文网\' onclick=\'_hmt.push([\'_trackEvent\', \'link\', \'click\', \'Laravel中文网\'])\' target=\'_blank\'>Laravel中文网</a>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("");
document.writeln("            <div class=\'col-sm-4\'>");
document.writeln("                <div class=\'widget\'>");
document.writeln("                    <h4 class=\'title\'>我们用到的技术</h4>");
document.writeln("                    <div class=\'content tag-cloud\'>");
document.writeln("                        <a href=\'http://www.bootcss.com/\' title=\'Bootstrap中文网\' onclick=\'_hmt.push([\'_trackEvent\', \'link\', \'click\', \'Bootstrap中文网\'])\' target=\'_blank\'>Bootstrap</a>");
document.writeln("                        <a href=\'http://www.ghostchina.com/\' title=\'Ghost中国\' onclick=\'_hmt.push([\'_trackEvent\', \'link\', \'click\', \'Ghost中国\'])\' target=\'_blank\'>Ghost</a>");
document.writeln("                        <a href=\'http://www.bootcdn.cn/\' title=\'BootCDN\' onclick=\'_hmt.push([\'_trackEvent\', \'link\', \'click\', \'BootCDN\'])\' target=\'_blank\'>BootCDN</a>");
document.writeln("                        <a href=\'http://www.gruntjs.net/\' title=\'Grunt中文网\' onclick=\'_hmt.push([\'_trackEvent\', \'link\', \'click\', \'Grunt中文网\'])\' target=\'_blank\'>Grunt</a>");
document.writeln("                        <a href=\'http://www.jquery123.com/\' title=\'jQuery中文文档\' onclick=\'_hmt.push([\'_trackEvent\', \'link\', \'click\', \'jQuery中文文档\'])\' target=\'_blank\'>jQuery</a>");
document.writeln("                        <a href=\'http://lodashjs.com/\' title=\'lodash中文网\' onclick=\'_hmt.push([\'_trackEvent\', \'link\', \'click\', \'Lodash中文网\'])\' target=\'_blank\'>Lodash</a>");
document.writeln("                        <a href=\'http://www.gulpjs.com.cn/\' title=\'Gulp中文网\' onclick=\'_hmt.push([\'_trackEvent\', \'link\', \'click\', \'Gulp中文网\'])\' target=\'_blank\'>Gulp</a>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("");
document.writeln("            <div class=\'col-sm-4\'>");
document.writeln("                <div class=\'widget\'>");
document.writeln("                    <h4 class=\'title\'>赞助商</h4>");
document.writeln("                    <div class=\'content friend-links\'>");
document.writeln("                        <a href=\'https://www.upyun.com/\' title=\'又拍云\' onclick=\'_hmt.push([\'_trackEvent\', \'link\', \'click\', \'又拍云\'])\' target=\'_blank\'>又拍云</a>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</footer>");
document.writeln("");